[package]
name = "hello_world"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.215", features = ["derive"] }
actix-web = "4.9.0"
shuttle-actix-web = "0.49.0"
shuttle-runtime = "0.49.0"
